version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-postgres-prisma-docker-p2
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - WS_JWT_SECRET=${WS_JWT_SECRET}
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - nestjs_network

  database:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: nest
    ports:
      - 5434:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge
volumes:
  postgres-data:
