services:
  - type: web
    name: nestjs-backend
    env: docker
    buildCommand: docker build -t nestjs-backend .
    startCommand: docker run -p 3000:3000 nestjs-backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: JWT_SECRET
        value: secret
      - key: JWT_REFRESH_SECRET
        value: secret refresh token
      - key: WS_JWT_SECRET
        value: web socket secret
    dockerfilePath: Dockerfile
    dockerComposeFilePath: docker-compose.yml
    dockerComposeService: backend
    databases:
      - name: postgres-db
        plan: starter-0
    healthCheckCommand: curl -f http://localhost:3000/health
