databases:
  - name: database
    databaseName: nest
    user: postgres_user
    postgresMajorVersion: 13

services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: '3000'
      - key: DATABASE_URL
        fromDatabase:
          type: database
          name: database
          envVarKey: RENDER_SERVICE_NAME
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
      - key: JWT_REFRESH_SECRET
        fromEnvVar: JWT_REFRESH_SECRET
      - key: WS_JWT_SECRET
        fromEnvVar: WS_JWT_SECRET
    buildCommand: ...
    startCommand: 'npm run start'
