services:
  - type: web
    name: nestjs-app
    env: docker
    buildCommand: docker build -t nestjs-app .
    startCommand: docker run -p 3000:3000 nestjs-app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: JWT_SECRET
        value: secret
      - key: JWT_REFRESH_SECRET
        value: secret refresh token
      - key: WS_JWT_SECRET
        value: web socket secret
