databases:
  - name: database
    databaseName: nest
    user: postgres_user
    postgresMajorVersion: 13

services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: '3000'
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: WS_JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
    buildCommand: docker build -t backend -f Dockerfile .
